import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ApiClientProvider } from "@repo/api-client";
import { I18nProvider } from "@repo/i18n/client";
import i18nConfig, {
  getT,
  getResources,
  initServerI18next,
} from "@repo/i18n/server";

initServerI18next(i18nConfig);

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { i18n, lng } = await getT();
  const resources = getResources(i18n);

  return (
    <I18nProvider language={lng} resources={resources}>
      <html lang={lng}>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <ApiClientProvider>{children}</ApiClientProvider>
        </body>
      </html>
    </I18nProvider>
  );
}
