import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ApiClientProvider } from "@repo/api-client";
import { I18nProvider } from "@repo/i18n/client";
import i18nConfig, {
  getT,
  getResources,
  initServerI18next,
} from "@repo/i18n/server";
import { Montserrat } from "next/font/google";
import { cn } from "@repo/utils";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-sans" });

initServerI18next(i18nConfig);

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { i18n, lng } = await getT();

  if (process.env.NODE_ENV === "development") {
    await i18n.reloadResources();
  }

  const resources = getResources(i18n);

  return (
    <I18nProvider language={lng} resources={resources}>
      <html lang={lng} className={cn("dark font-sans", montserrat.variable)}>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <ApiClientProvider>{children}</ApiClientProvider>
        </body>
      </html>
    </I18nProvider>
  );
}
